### ISSUE TITLE
 Implement Pet Deletion Endpoint

### ISSUE THREAD

**Issue by System-Garcia** [System-Garcia/node-pets#19]
**Objective:** Develop the endpoint for deleting pet profiles, ensuring that only the pet owner can delete the pet profile.

**Requirements:**
- [x] Create a new endpoint for pet profile deletion in the backend.
- [x] Ensure the deletion process checks for ownership of the pet profile.
- [x] Implement soft deletion to maintain data integrity for historical purposes.
- [x] Verify that only authenticated and authorized users can delete pet profiles.

**Acceptance Criteria:**
- The endpoint correctly identifies and validates the pet owner before deletion.
- Pet profiles are not permanently removed from the database; instead, they are marked as deleted (soft deletion).
- Only authenticated and authorized users (pet owners) can successfully delete a pet profile.
- The system provides appropriate feedback/error messages if the deletion attempt fails due to unauthorized access or other issues.

**Comment by System-Garcia** [comment]
Resolved in #69

**Comment by ivanchenoweth** [comment]
No tiene PR asignado , ni fechas de inicio y fin, endpoint proposal?
