### ISSUE TITLE
Implement Pet Update Endpoint

### ISSUE THREAD

**Issue by System-Garcia** [System-Garcia/node-pets#22]
**Objective:** Develop the endpoint for updating existing pet profiles, ensuring that only the pet owner can update the pet's information.

**Requirements:**
- [x] Implement an endpoint to update pet profiles, including fields such as name, species, color, and image URL.
- [x] Validate input data for completeness and adherence to the required format.
- [x] Ensure the update operation verifies the ownership of the pet profile before proceeding with the update.
- [x] Restrict update capabilities to authenticated and authorized users, confirming they are the pet's owner.
- [x] Implement logic to handle partial updates (e.g., using HTTP PATCH) or full updates (e.g., using HTTP PUT) as appropriate.

**Acceptance Criteria:**
- Pet profile updates can only be performed by the pet's owner, with ownership verification implemented.
- Input data for updates is validated to ensure it meets specified criteria.
- The endpoint supports both partial and full updates of pet profiles.
- Only authenticated and authorized users are able to update pet profiles.
- Appropriate feedback/error messages are returned if the update attempt fails due to reasons like unauthorized access, invalid data, or other issues.

**Comment by System-Garcia** [comment]
Resolved in #72

**Comment by ivanchenoweth** [comment]
No tiene PR asignado , ni fechas de inicio y fin, ni milestone
