### ISSUE TITLE
Design Species Management Page

### ISSUE THREAD

**Issue by System-Garcia** [System-Garcia/node-pets#27]
**Objective:** Design the UI for a species management page for administrators.

**Requirements:**
- [x] Design an intuitive interface for adding, listing, updating, and deleting species.
- [x] Include forms for adding and editing species information.
- [x] Ensure the design is consistent with the application's overall style.

**Acceptance Criteria:**
- The species management page is user-friendly and intuitive.
- Administrators can easily navigate to add, update, and delete species.
- The design is consistent with the rest of the application.

**Comment by iGEVA** [comment]
#83
