### ISSUE TITLE
Implement Species Listing on Management Page

### ISSUE THREAD

**Issue by System-Garcia** [System-Garcia/node-pets#28]
**Objective:** Implement the functionality to list all species on the management page.

**Requirements:**
- [x] Fetch and display a list of all species from the backend.
- [x] Ensure the listing is updated in real-time after adding, updating, or deleting species.

**Acceptance Criteria:**
- All species are listed on the management page.
- The listing reflects real-time changes to the species database.

**Comment by iGEVA** [comment]
#84

**Comment by ivanchenoweth** [comment]
No tiene PR asignado , ni fechas de inicio y fin, ni milestone, mockups

**Comment by iGEVA** [comment]
#90
