### ISSUE TITLE
Create Location on Reward Creation

### ISSUE THREAD

**Issue by System-Garcia** [System-Garcia/node-pets#33]
**Objective:** Automate the creation of location entries in the database as part of the reward creation process, ensuring that only authorized users can create rewards and associated locations.

**Requirements:**
- [x] Modify the reward creation endpoint to accept location data (address, city, country) along with reward details.
- [x] Implement logic to create a new location in the database using the provided location details before creating the reward.
- [x] Ensure the reward is linked to the newly created location by storing the location's ID with the reward.

**Acceptance Criteria:**
- Location details provided with reward creation requests result in new locations being created in the database.
- Newly created rewards are correctly linked to the newly created locations.
- Unauthorized users cannot create rewards or locations.

**Comment by System-Garcia** [comment]
Resolved in #75

**Comment by ivanchenoweth** [comment]
No tiene PR asignado , ni fechas de inicio y fin, ni milestone
