### ISSUE TITLE
Implement Reward Deletion

### ISSUE THREAD

**Issue by System-Garcia** [System-Garcia/node-pets#40]
**Objective:** Provide functionality for users to delete their rewards, handling associated data appropriately.

**Requirements:**
- [x] Create an endpoint for reward deletion by ID.
- [x] Verify that the requesting user is the owner of the reward.
- [x] Consider the handling of associated location data, ensuring no adverse effects on shared locations.

**Acceptance Criteria:**
- Users can delete their own rewards.
- Deletion requests are authenticated and authorized, preventing unauthorized deletions.
- The system intelligently handles associated locations, preserving data integrity.

**Comment by System-Garcia** [comment]
Resolved in #78

**Comment by ivanchenoweth** [comment]
No tiene PR asignado , ni fechas de inicio y fin, ni milestone
