### ISSUE TITLE
Refactor: AuthContext and AxiosHelper

### ISSUE THREAD

**Issue by iGEVA** [System-Garcia/node-pets#86]
### Refactor `AuthProvider`

**Objective:**  
Refactor the `AuthProvider` component to improve the security of token handling, streamline state management, and enhance error reporting for a better user experience.

**Requirements:**
- [x] Ensure that tokens are stored securely, considering alternatives to `localStorage` such as cookies with HttpOnly and Secure attributes.
- [x] Refactor the `login` and `logout` methods to handle authentication states more predictably, ensuring state consistency across the application.
- [x] Enhance error handling in the `login` method to provide more descriptive and user-friendly error messages.
- [x] Include thorough unit tests for the `AuthProvider`, especially focusing on the `login` and `logout` functionalities.

**Acceptance Criteria:**
- Secure storage mechanisms are used for sensitive information, reducing the risk of XSS attacks.
- Authentication state transitions are handled smoothly, with proper updates and validations reflected in the UI.
- Errors during login are clearly communicated to the user, improving their ability to troubleshoot issues.
- The component's functionality is confirmed with a comprehensive set of unit tests, ensuring reliability and ease of future modifications.

### Refactor `httpHelper`

**Objective:**  
Enhance the `httpHelper` utility to improve flexibility, error handling, and ensure easy integration and testing within the application architecture.

**Requirements:**
- [x] Implement comprehensive error handling across all HTTP methods, standardizing the error structure returned to the caller.
- [x] Enhance configurability of the `axiosInstance`, including support for dynamic headers, timeouts, and other HTTP configurations.
- [x] Ensure `httpHelper` includes support for interceptors for centralized request modifications and error logging.
- [x] Design `httpHelper` to be easily testable, facilitating the development of unit tests for components that depend on network requests.

**Acceptance Criteria:**
- `httpHelper` adapts to different backend communication needs with high flexibility and reliability.
- Error handling is robust, with standardized responses that aid in debugging and user feedback.

**Comment by System-Garcia** [comment]
Resolved in #87
